import { Component } from '@angular/core';

@Component({
  selector: 'app-shop-com',
  standalone: true,
  imports: [],
  templateUrl: './shop-com.component.html',
})
export class ShopComComponent {
  products = [
    {
      name: 'Piqué Biker Jacket',
      price: 67.24,
      imgUrl: 'url(../../../../img/product/product-2.jpg)',
      category: '',
      gender: '',
      brand: '',
      sale: false,
    },
    {
      name: 'Multi-pocket Chest Bag',
      price: 43.48,
      imgUrl: 'url(../../../../img/product/product-3.jpg)',
      category: '',
      gender: '',
      brand: '',
      sale: true,
    },
    {
      name: 'Diagonal Textured Cap',
      price: 60.9,
      imgUrl: 'url(../../../../img/product/product-4.jpg)',
      category: '',
      gender: '',
      brand: '',
      sale: true,
    },
    {
      name: 'Ankle Boots',
      price: 98.49,
      imgUrl: 'url(../../../../img/product/product-6.jpg)',
      category: '',
      gender: '',
      brand: '',
      sale: false,
    },
    {
      name: 'T-shirt Contrast Pocket',
      price: 49.66,
      imgUrl: 'url(../../../../img/product/product-7.jpg)',
      category: '',
      gender: '',
      brand: '',
      sale: true,
    },
    {
      name: 'Basic Flowing Scarf',
      price: 26.28,
      imgUrl: 'url(../../../../img/product/product-8.jpg)',
      category: '',
      gender: '',
      brand: '',
      sale: false,
    },
    {
      name: 'Piqué Biker Jacket',
      price: 67.24,
      imgUrl: 'url(../../../../img/product/product-9.jpg)',
      category: '',
      gender: '',
      brand: '',
      sale: true,
    },
    {
      name: 'Multi-pocket Chest Bag',
      price: 43.48,
      imgUrl: 'url(../../../../img/product/product-10.jpg)',
      category: '',
      gender: '',
      brand: '',
      sale: false,
    },
    {
      name: 'Diagonal Textured Cap',
      price: 60.24,
      imgUrl: 'url(../../../../img/product/product-11.jpg)',
      category: '',
      gender: '',
      brand: '',
      sale: true,
    },
    {
      name: 'Diagonal Textured Cap',
      price: 98.24,
      imgUrl: 'url(../../../../img/product/product-12.jpg)',
      category: '',
      gender: '',
      brand: '',
      sale: true,
    },
    {
      name: 'T-shirt Contrast Pocket',
      price: 49.66,
      imgUrl: 'url(../../../../img/product/product-13.jpg)',
      category: '',
      gender: '',
      brand: '',
      sale: true,
    },
    {
      name: 'Basic Flowing Scarf',
      price: 26.28,
      imgUrl: 'url(../../../../img/product/product-14.jpg)',
      category: '',
      gender: '',
      brand: '',
      sale: false,
    },
  ];
}
